[package]
name = "open-rpc-spec-types"
version = "0.0.2"
edition = "2021"
description = "Generated OpenRPC specification types"
license = "Apache-2.0"

[dependencies]
serde_json = "1.0"
derive_builder = "0.20"

  [dependencies.serde]
  version = "1.0"
  features = [ "derive" ]
