[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"

[project]
name = "open-rpc-spec-types"
version = "0.0.1"
description = "Generated OpenRPC specification types"
license = "Apache-2.0"
requires-python = ">=3.12"
